feat(vertexai): support model garden and tuned models names
googleapis/google-cloud-go pull request #10197
Opened 2024-05-16 14:11 UTC by eliben

Re #9630

2024-05-16 19:04 UTC, jba requested changes

2024-05-16 19:04 UTC, jba commented on vertexai/genai/client.go
> +	return fullName
A bit more idiomatically:
```
if !strings.HasPrefix(pubName, ...) {
    return pubName
}
return fmt.Sprintf("....")
```

2024-05-16 21:15 UTC, eliben commented on vertexai/genai/client.go
> +// inferModelName infers the full model name (with all the required prefixes)
Done

2024-05-16 21:15 UTC, eliben commented on vertexai/genai/client.go
> +	return fullName
Done

2024-05-17 12:08 UTC, jba approved these changes

2024-05-17 13:14 UTC, merged