fix(auth): add back DirectPath misconfiguration logging
googleapis/google-cloud-go pull request #11162
Opened 2024-11-20 22:32 UTC by xmenxk

https://github.com/googleapis/google-cloud-go/issues/11001

2024-11-20 22:34 UTC, xmenxk commented
This follows the PR in https://github.com/googleapis/google-api-go-client/pull/2225

2024-11-21 01:35 UTC, codyoss commented on auth/grpctransport/directpath.go
> +		log.Println("WARNING: DirectPath is disabled. To enable, please set the EnableDirectPath option along with the EnableDirectPathXds option.")
prefer: https://pkg.go.dev/log/slog#Warn

2024-11-23 00:36 UTC, xmenxk commented on auth/grpctransport/directpath.go
> +		log.Println("WARNING: DirectPath is disabled. To enable, please set the EnableDirectPath option along with the EnableDirectPathXds option.")
done!

2025-01-13 23:28 UTC, BrennaEpp commented
Is there something remaining for this PR to be ready?

2025-01-13 23:42 UTC, xmenxk commented
> Is there something remaining for this PR to be ready?

@codyoss ptal

2025-01-14 15:20 UTC, codyoss requested changes

2025-01-14 15:20 UTC, codyoss commented on auth/grpctransport/directpath.go
> +		slog.Warn("DirectPath is disabled. To enable, please set the EnableDirectPath option along with the EnableDirectPathXds option.")
We now have a general logging pattern. Please access the logger via o.logger().

2025-02-10 23:34 UTC, quartzmo commented
@xmenxk What is the status of this PR? Do you need assistance?

2025-05-29 21:11 UTC, quartzmo approved these changes

2025-06-02 20:17 UTC, quartzmo commented
vet is still failing:

```
--- a/auth/go.mod
+++ b/auth/go.mod
@@ -11,6 +11,7 @@ require (
 	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.61.0
 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.61.0
 	golang.org/x/net v0.40.0
+	golang.org/x/time v0.5.0
 	google.golang.org/grpc v1.72.1
 	google.golang.org/protobuf v1.36.6
 )
```

2025-06-03 15:48 UTC, codyoss commented
Besides the panic looks good: 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd0057d]

goroutine 13 [running]:
testing.tRunner.func1.2({0x1030320, 0x180a690})
	/usr/local/go/src/testing/testing.go:1734 +0x3eb
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1737 +0x696
panic({0x1030320?, 0x180a690?})
	/usr/local/go/src/runtime/panic.go:787 +0x132
cloud.google.com/go/auth.(*Credentials).Token(0x0, {0x127e6f0, 0x184db80})
	:1 +0x3d
cloud.google.com/go/auth/grpctransport.isTokenProviderComputeEngine({0x1275740, 0x0})
	/tmpfs/src/google-cloud-go/auth/grpctransport/directpath.go:67 +0x4d
cloud.google.com/go/auth/grpctransport.isTokenProviderDirectPathCompatible(...)
	/tmpfs/src/google-cloud-go/auth/grpctransport/directpath.go:90
cloud.google.com/go/auth/grpctransport.logDirectPathMisconfig({0x1139d8c, 0x12}, 0x0, 0xc000145e20)
	/tmpfs/src/google-cloud-go/auth/grpctransport/directpath.go:169 +0xd3
cloud.google.com/go/auth/grpctransport.TestLogDirectPathMisconfigWrongCredential(0xc000165180)
	/tmpfs/src/google-cloud-go/auth/grpctransport/directpath_test.go:191 +0x4c5
testing.tRunner(0xc000165180, 0x116c700)
	/usr/local/go/src/testing/testing.go:1792 +0x226
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1851 +0x8f3
FAIL	cloud.google.com/go/auth/grpctransport	0.044s
```

2025-06-03 22:32 UTC, merged