feat(bigtable): Incrementable values
googleapis/google-cloud-go pull request #3493
Opened 2020-12-30 01:21 UTC by AlisskaPie

2021-01-12 19:14 UTC, billyjacobson commented
Looks good from a Bigtable perspective

2021-02-11 17:47 UTC, billyjacobson commented
@tbpg This looks good on my end, could you give it a language review? Thanks

2021-02-26 17:35 UTC, tbpg requested changes

2021-02-26 17:35 UTC, tbpg commented on bigtable/bigtable.go
> +func (m *Mutation) SetInt64(family, column string, ts Timestamp, value int) {
Seems like this should be an `int64` argument if we always treat it as an `int64`, especially given the name of the method?

2021-02-26 17:35 UTC, tbpg commented on bigtable/bigtable.go
> +	buf := new(bytes.Buffer)
```suggestion
	var buf bytes.Buffer
```

2021-02-26 17:35 UTC, tbpg commented on bigtable/bigtable.go
> +	binary.Write(buf, binary.BigEndian, int64(value))
`Write` returns an error -- we should check it.

2021-02-26 17:35 UTC, tbpg commented on bigtable/filter.go
> +func ValueFilterInt64(pattern int) Filter {
Same `int64` argument and `binary.Write` comments here and for `ValueRangeFilterInt64`.

2021-02-26 17:35 UTC, tbpg commented on bigtable/bigtable.go
> +func (m *Mutation) SetInt64(family, column string, ts Timestamp, value int) {
Looks like we need tests for this.

2021-09-28 18:50 UTC, closed without merging