feat(gsuiteaddons): start generating apiv1
googleapis/google-cloud-go pull request #4082
Opened 2021-05-10 20:51 UTC by codyoss

2021-05-18 15:10 UTC, codyoss commented
cc @tbpg

2021-05-20 19:07 UTC, tbpg requested changes
Would you mind updating this filter, as this does not appear to be a Cloud API?

https://github.com/googleapis/google-cloud-go/blob/258980a039db26c5a1761efdb65109a52dfdd83e/internal/godocfx/main.go#L151-L154

2021-05-27 12:23 UTC, tbpg approved these changes

2021-05-27 12:23 UTC, tbpg commented on internal/godocfx/main.go
> +		"cloud.google.com/go/gsuiteaddons/apiv1",
```suggestion
		"cloud.google.com/go/gsuiteaddons",
```

So we don't have to update this for new versions in the future. The filter is prefix based.

2021-05-27 14:31 UTC, merged