pubsub: Add Publisher and Subscriber interfaces which are shared by Pub/Sub and Pub/Sub Lite
googleapis/google-cloud-go pull request #4171
Opened 2021-05-26 15:35 UTC by dpcollins-google

Fixes #4141

2021-05-26 15:35 UTC, dpcollins-google commented
@hongalex

2021-05-26 15:37 UTC, dpcollins-google commented
manually set the CLA: The coauthor is me, just poorly configured in git.

2021-05-27 17:26 UTC, hongalex commented
What do you think we should do should we ever want to add new methods to this interface (which would be a breaking change)? Are we confident in the stability of publisher/subscriber interfaces that we won't ever add new methods?

@codyoss @shollyman Do you know of examples of exposing interfaces like this in other libraries?

2021-05-27 17:51 UTC, codyoss commented
We purposefully do not export interfaces for our clients the reasons @hongalex mentioned above -- breaking changes. If you really wanted to asset a common interface I would make it private in internal.

2021-05-27 17:51 UTC, codyoss requested changes
See comment above about interfaces in Go.

2021-06-15 11:42 UTC, tmdiep commented on pubsublite/pscompat/subscriber.go
> +type MessageReceiverFunc = pubsub.MessageReceiverFunc
If there are no objections to defining MessageReceiverFunc in the pubsub package, we could just remove this and change the parameter of SubscriberClient.Receive() to pubsub.MessageReceiverFunc. Any extra comments here can just be moved to SubscriberClient.Receive().

2021-06-17 23:55 UTC, tmdiep commented
I just looked at the test failures for this PR and realized that they caught a breaking change. We need to declare `type MessageReceiverFunc = func(context.Context, *Message)` in `pubsub` (note: add = to define as an alias). If declared as `type MessageReceiverFunc func(context.Context, *Message)`, this breaks any users' existing interfaces (I confirmed with a test).

I now think that we should just leave `pubsub` as-is and make `pubsublite`'s interfaces identical. I made this change in  https://github.com/googleapis/google-cloud-go/pull/4281, and also added examples for users to copy, which also have the benefit of triggering compilation errors.

2021-06-17 23:56 UTC, tmdiep commented on pubsublite/pscompat/subscriber.go
> +type MessageReceiverFunc = pubsub.MessageReceiverFunc
Retracting, see comment below.

2021-11-08 21:55 UTC, closed without merging