feat(internal/carver): add tooling to help carve out sub-modules
googleapis/google-cloud-go pull request #4417
Opened 2021-07-12 19:47 UTC by codyoss

2021-07-12 19:53 UTC, codyoss commented
Here is an example PR that was raised the code: https://github.com/googleapis/google-cloud-go/pull/4419

Steps:

1. Ran:
```bash
go run cmd/main.go \
  -parent=/path/to/google-cloud-go \
  -child=asset \
  -repo-metadata=/path/to/google-cloud-go/internal/.repo-metadata-full.json
```

2. Ran `git push remote branch`.
3. After PR is merged run: `git push remote --tags`

2021-07-16 13:44 UTC, tbpg requested changes

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/_CHANGES.md.txt
> +This is the first tag to carve out {{.Package}} as its own module. See:
```suggestion
This is the first tag to carve out {{.Package}} as its own module. See
```

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/_README.md.txt
> +## Import
This is how to `get`, not to `import`.

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/_README.md.txt
> +package documentation.
I feel like we can be more clear here. Suggestion, feel free to edit further:

```suggestion
The stability of this module is indicated by SemVer.

However, a `v1+` module may have breaking changes in two scenarios:

* Packages with `alpha` or `beta` in the import path
* The GoDoc has an explicit stability disclaimer (for example, for an experimental feature).
```

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/_README.md.txt
> +Contributions are welcome. Please, see the[CONTRIBUTING](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md)
```suggestion
Contributions are welcome. Please, see the [CONTRIBUTING](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md)
```

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +		return fmt.Errorf("all required flags were not provided")
Say what wasn't included?

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +	fp2 := filepath.Join(c.childModPath, "CHANGES.md")
Perhaps better names than `fp` and `fp2` etc. are in order? :smile:

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +	if !c.dryRun {
Should dry run print the things it would do if it weren't a dry run?

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +	sort.Slice(tags, func(i, j int) bool {
Use https://pkg.go.dev/golang.org/x/mod/semver?

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +func parsePkgName(importPath string) (string, error) {
This is more like `guessPkgName` since the name may not always be the final element of the import path. Is there a better way?

2021-07-16 13:44 UTC, tbpg commented on internal/carver/cmd/main.go
> +			return fmt.Errorf("unable to determine a name from API metadata, please set -name flag")
Give path to metadata file? And the import path that was being looked for?

2021-07-26 14:55 UTC, tbpg approved these changes

2021-07-26 16:20 UTC, merged