test(storage): add buckets to fix failing test
googleapis/google-cloud-go pull request #4903
Opened 2021-09-28 23:54 UTC by BrennaEpp

Fixes #4720

* Added two buckets to use in the test to avoid the per bucket rate limit
* Made clearer how we are using the third project ("veener-jba")
* Added a couple comment

2021-09-29 14:41 UTC, codyoss requested changes
Just a couple of small things.

2021-09-29 14:41 UTC, codyoss commented on storage/integration_test.go
> +	//t.Skip("https://github.com/googleapis/google-cloud-go/issues/4720")
nit: Just delete the skip.

2021-09-29 14:41 UTC, codyoss commented on storage/integration_test.go
> +	b2a := otherClient.Bucket(bucketName2)
Does this need a cleanup associated with it?

2021-09-29 16:06 UTC, codyoss approved these changes

2021-11-01 20:14 UTC, BrennaEpp commented on storage/integration_test.go
> +	user := jwt.Email
It's used on L2834 for an error message

2021-11-01 22:53 UTC, tritone approved these changes

2021-11-01 22:53 UTC, merged