feat(run): start generating apiv2
googleapis/google-cloud-go pull request #5825
Opened 2022-03-30 21:44 UTC by quartzmo

2022-03-31 18:56 UTC, codyoss requested changes
Just one small thing that I think will make release-please a little happier

2022-03-31 18:56 UTC, codyoss commented on run/internal/version.go
> +const Version = "0.1.0"
Would you mind manually changing this to 0.0.0. We should also update the template in a future CL to do the same

2022-03-31 22:11 UTC, codyoss commented on run/CHANGES.md
> +## v0.1.0
manually update to remove this entry

2022-03-31 22:57 UTC, quartzmo commented on run/CHANGES.md
> +## v0.1.0
Done, thanks!

2022-04-01 13:45 UTC, codyoss approved these changes

2022-04-01 13:59 UTC, merged