docs: add Google Cloud Samples browser link to readme template
googleapis/google-cloud-go pull request #6015
Opened 2022-05-09 13:00 UTC by msampathkumar

Adding a generic Google Code Sample link to readme template.

This is for the benefit of the users, in navigating available Google Cloud code samples.

2022-05-09 14:57 UTC, codyoss requested changes
Just one small thing.

2022-05-09 14:57 UTC, codyoss commented on internal/gapicgen/generator/_README.md.txt
> +To browse ready to use code samples check [Google Cloud Samples](https://cloud.google.com/docs/samples).
Let's make this Go specific: https://cloud.google.com/docs/samples?l=go

2022-05-12 14:08 UTC, msampathkumar commented
@codyoss - Updated the link to be go-specific. Thank you :)

2022-05-12 14:25 UTC, codyoss approved these changes
Thanks!

2022-05-12 14:25 UTC, merged