chore(pubsublite): mark pubsublite library as GA
googleapis/google-cloud-go pull request #6182
Opened 2022-06-15 21:54 UTC by hongalex

The Lite library was already GA for a while, just needed to update this json file

2022-06-15 23:00 UTC, tmdiep approved these changes

2022-06-15 23:05 UTC, noahdietz approved these changes

2022-06-16 01:32 UTC, codyoss requested changes
Please update the value here also: https://github.com/googleapis/google-cloud-go/blob/main/internal/gapicgen/generator/gapics.go#L527

That is the source of truth that generated the metadata file.

2022-09-26 20:43 UTC, meredithslota commented
Relevant value is now https://github.com/googleapis/google-cloud-go/blob/main/internal/gapicgen/generator/gapics.go#L576

2022-09-27 15:38 UTC, codyoss approved these changes

2022-09-28 23:14 UTC, merged