feat: enable compression for pubsublite publish
googleapis/google-cloud-go pull request #7545
Opened 2023-03-14 15:19 UTC by dpcollins-google

This is the equivalent of https://github.com/googleapis/java-pubsublite/pull/1360

2023-03-17 11:54 UTC, tmdiep requested changes

2023-03-17 11:54 UTC, tmdiep commented on pubsublite/pscompat/settings.go
> +	DisableCompression bool
Can you change this to `EnableCompression optional.Bool` for consistency with EnableIdempotence in https://github.com/googleapis/google-cloud-go/pull/7390/files (not merged yet).

Also, if you haven't already, could you ensure the integration tests pass by running locally in the `pscompat` dir: `go test -race -v`. The presubmit checks run tests with `-short`, which skips the integration tests.

Also, looks like the unit tests need updating: https://source.cloud.google.com/results/invocations/6d293971-fecf-4018-bfc8-9d753e586309/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Flatest-version/log

2023-03-17 12:40 UTC, tmdiep commented on pubsublite/pscompat/settings.go
> +	DisableCompression bool
I just merged the idempotence PR.

2024-04-23 14:33 UTC, codyoss commented
Is this still needed or should we close it?

2024-05-22 17:07 UTC, closed without merging